---
title: "R Notebook"
output: html_notebook
---
#Modeling Notebook

```{r}
weather <- Washington_DC_USA_weather_2022_08_01_to_2022_08_31
bikes <- read.csv("C:/Users/calvi/Downloads/202208-capitalbikeshare-tripdata/202208-capitalbikeshare-tripdata.csv")
```


```{r}
bikes
library(dplyr)
# data manipulation
head(bikes)
bikes$date <- substr(bikes$started_at, 1, 11)

mod_data <- bikes %>%
  group_by(date) %>%
  summarize(num_bikers = n())

mod_data
weather

mod_data$date <- as.Date(mod_data$date)
mod_data
weather

mod_data <- mod_data %>% inner_join(weather, by = c('date' = "datetime"))
mod_data
```

```{r}
# linear modeling
mod_1 = lm(num_bikers~tempmax+tempmin+temp+feelslike+dew+humidity+precip+windgust+windspeed+winddir+visibility+solarradiation+severerisk+uvindex, data = mod_data)
summary(mod_1)
# selecting non-overlapping features
mod_2 = lm(num_bikers~tempmin+feelslike+precip+winddir+uvindex, data = mod_data)
summary(mod_2)
# looks like performance is much better with all features
```
```{r}
# visualizing linear feature importance
library(dotwhisker)
dwplot(mod_1) +
  ggtitle("Linear Model Feature Coefficients") +
  labs(x = "Standardized Effect", y = "Feature Name", subtitle = "Large importance in precipitation, tempurature") +
  theme_classic() +
  geom_vline(xintercept = 0)

```


```{r}
# random forest regression
mod_data
install.packages("randomForest")
library(randomForest)
library(ggplot2)
rf.fit <- randomForest(num_bikers~tempmax+tempmin+temp+feelslike+dew+humidity+precip+
                         windgust+windspeed+winddir+visibility+solarradiation+severerisk+uvindex,
                       data=mod_data, ntree=1000,
                       keep.forest=FALSE, importance=TRUE)
rf.fit
rmse <- sqrt(1225608)
rmse

ImpData <- as.data.frame(importance(rf.fit))
ImpData$Var.Names <- row.names(ImpData)
varImpPlot(rf.fit)
```

```{r}

ggplot(ImpData, aes(x=Var.Names, y=`%IncMSE`)) +
  geom_segment( aes(x=Var.Names, xend=Var.Names, y=0, yend=`%IncMSE`), color="skyblue") +
  geom_point(aes(size = IncNodePurity), color="blue", alpha=0.6) +
  theme_light() +
  coord_flip() +
  theme(
    legend.position="bottom",
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )
```

```{r}
# regression with lightGBM (nerual net model)
# not going to do rn
#install.packages("lightgbm")
#install.packages("caret")
library(lightgbm)
library(caret)




 
```








