---
title: "R Notebook"
output: html_notebook
---

```{r}
weather <- read.csv(paste0("C:/Users/Ndidi/Desktop/2022-23/fall/STAT 405/data project/stat405-project/Washington,DC,USA weather 2022-08-01 to 2022-08-31.csv"))
library(stringr)
weather
```


```{r}
weather$cloudy <- as.factor(as.numeric(str_detect(weather$description, "cloud")))
weather$clear <- as.factor(as.numeric(str_detect(weather$description, "Clear")))
weather$rain <- as.factor(as.numeric(str_detect(weather$description, "rain")))
```

```{r}
library(RSQLite)
dcon <- dbConnect(SQLite(), dbname = "mydba.sqlite")
table <- read.csv(paste0("C:/Users/Ndidi/Desktop/2022-23/fall/STAT 405/data project/stat405-project/Washington,DC,USA weather 2022-08-01 to 2022-08-31.csv"))
dbWriteTable(conn = dcon, name = "weather", 
             table, append = TRUE, row.names = FALSE)
dbListTables(dcon)
table2 <- read.csv("C:/Users/Ndidi/Desktop/2022-23/fall/STAT 405/202208-capitalbikeshare-tripdata/202208-capitalbikeshare-tripdata.csv", header = TRUE, sep = ",")
dbWriteTable(conn = dcon, name = "bikes", 
             table2, append = TRUE, row.names = FALSE)
dbListTables(dcon)
#dbDisconnect(conn = dcon)
```


```{r}
table2$date <- str_sub(table2$started_at, 1, 10)
bikes <- table2
library(margins)
library(dplyr)
# aggregating by rides per day
by_date <- bikes %>%
  group_by(date) %>%
  summarise(total_rides = n()) 
weather$date <- as.Date(weather$datetime)
by_date$date <- by_date$date
dates <- by_date$date
by_date$date <- as.POSIXct(dates,tz=Sys.timezone())
# joining weather data with bike data
ride_weather <- inner_join(by_date, weather)
ride_weather
```
```{r}
# look at relationship between weather aspects and total rides
library(ggplot2)
library(ggeffects)
mod <- lm(total_rides ~ rain+clear+cloudy, data = ride_weather)
summary(mod)
# creating a substantive effect plot
p<-ggpredict(mod, "rain")
plot(p) +
  ggtitle("Effect of Rain on Rides Per Day") +
  labs(y = "Number of Rides Per Day", x = "Pressence of Rain", 
       subtitle = "Visualizing the significant decrease of rides on rainy days") +
  theme_ggeffects()

```

```{r}
library(dotwhisker)
dwplot(mod, vline = geom_vline(xintercept = 0, colour = "grey60", linetype = 2))%>% 
  relabel_predictors(c(rain1= "Rain", clear1 = "Clear",cloudy1 = "Cloudy")) +
  ggtitle("Effects of Weather Description Factors on Rides")
```


















